server:
  port: 28080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/store?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&nullCatalogMeansCurrent=true&rewriteBatchedStatements=true
    username: root
    password: roOt^123456#
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1 # Redis 服务器地址, 默认
      port: 26379 # 端口, 默认6379
      database: 0 # 数据库索引(0-15,默认0)
      password: # 默认为空
      timeout: 5000ms # 超时时间, 默认
      lettuce:
        pool:
          max-active: 8 # 连接池最大连接数 (负数表示没有限制), 默认
          max-wait: -1ms  # 连接池最大阻塞等待时间 (负数表示没有限制), 默认
          max-idle: 8 # 连接池中的最大空闲连接, 默认
          min-idle: 0 # # 连接池中的最小空闲连接, 默认

      # sql: # MySQL初始化配置
    # init:
      # schema-locations: classpath:sql/store.sql # 数据库创建语句
      # data-locations: classpath:sql/store-data.sql # 数据源

--- ############ JWT 配置 ##############################
jwt:
  secret: "171+jiDgyJvgsvwJXM93kvNIEfJHy3-sKGM9mJ9XsSpwfaN9mld2DxN4/ESIzx5u" # JWT 加密密钥 (至少32字节)
  expire-time: 24h # Token 过期时间, 1天(1d或24h)
  refresh-expire-time: 168h # Refresh Token 过期时间, 7天(7d或168h)

--- ########## MyBatis-plus 配置 ########################
mybatis-plus:
  # mapper-locations: classpath*:/mapper/**/*.xml
  # type-aliases-package: online.store.pojo
  global-config:
    db-config:
      id-type: ASSIGN_ID # 默认值。自动分配 ID，适用于 Long、Integer、String 类型的主键。默认使用雪花算法通过 IdentifierGenerator 的 nextId 实现。详见 https://baomidou.com/reference/#dbconfig
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

--- ################ Springdoc 配置 (Swagger UI) 生成接口文档 ##############
springdoc:
  api-docs:
    path: /v3/api-docs # 默认值
  swagger-ui:
    enabled: true # 是否启用 Swagger UI，默认值为 true
    path: /swagger-ui.html # 默认值 http://{ip}:{port}/{ContextPath}/swagger-ui.html http://localhost:28080/swagger-ui.html
    tryItOutEnabled: false # 是否启用 "Try it out" 按钮，默认值为 false
    operationsSorter: alpha # 按路径字母顺序排序, 可选值：alpha, method, none, 函数
    tagsSorter: alpha # 按标签字母顺序排序, 可选值：alpha, method, none, 函数
    displayRequestDuration: true # 显示在"Try it out"请求中请求持续时间(ms)，默认值为 false
    deepLinking: false # 是否启用深度链接，默认值为 false
#knife4j增强配置
knife4j:
  enable: true # 是否开启, 默认 false http://{ip}:{port}/doc.html
  setting:
    language: zh_cn # i18n 语言, 简体中文
    enable-swagger-models: true
    swagger-model-name: "在线购物商城API"

logging:
  level:
    root: INFO
    org.apache.tomcat: DEBUG
    org.apache.catalina: DEBUG
    com.baomidou.mybatisplus: DEBUG
    online.store: INFO